spring.datasource.url=jdbc:postgresql://localhost:5432/busway
spring.datasource.username=postgres
spring.datasource.password=busway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.default-property-inclusion=non_null